
#Spawning settings
[Spawning]

	#AntHill settings
	[Spawning.AntHill]
		#The spawning weight of AntHill's (0 = disabled) [default: 20]
		#Range: > 0
		anthillWeight = 20
		#The minimum number of AntHill's in a group [default: 1]
		#Range: > 1
		anthillMinGroup = 1
		#The maximum number of AntHill's in a group [default: 1]
		#Range: > 1
		anthillMaxGroup = 1
		#The biomes where AntHill's can spawn
		anthillBiomes = ["minecraft:desert"]
		#The biome's matching the biome dictionary entries in which AntHill's can spawn
		anthillBiomeDictionary = ["OVERWORLD,SANDY,!MESA"]
		#Inverts the AntHill biome list to become a blacklist instead (Does not affect tags) [default: false]
		anthillInvertList = false
		#Logs to which biomes AntHill is being added [default: false]
		anthillLogAdditions = false

	#Anubis settings
	[Spawning.Anubis]
		#The spawning weight of Anubis's (0 = disabled) [default: 80]
		#Range: > 0
		anubisWeight = 80
		#The minimum number of Anubis's in a group [default: 2]
		#Range: > 1
		anubisMinGroup = 2
		#The maximum number of Anubis's in a group [default: 4]
		#Range: > 1
		anubisMaxGroup = 4
		#The biomes where Anubis's can spawn
		anubisBiomes = ["minecraft:desert"]
		#The biome's matching the biome dictionary entries in which Anubis's can spawn
		anubisBiomeDictionary = ["OVERWORLD,SANDY,!MESA"]
		#Inverts the Anubis biome list to become a blacklist instead (Does not affect tags) [default: false]
		anubisInvertList = false
		#Logs to which biomes Anubis is being added [default: false]
		anubisLogAdditions = false

	#Centaur settings
	[Spawning.Centaur]
		#The spawning weight of Centaur's (0 = disabled) [default: 80]
		#Range: > 0
		centaurWeight = 80
		#The minimum number of Centaur's in a group [default: 2]
		#Range: > 1
		centaurMinGroup = 2
		#The maximum number of Centaur's in a group [default: 4]
		#Range: > 1
		centaurMaxGroup = 4
		#The biomes where Centaur's can spawn
		centaurBiomes = ["minecraft:plains", "minecraft:sunflower_plains", "minecraft:badlands", "minecraft:eroded_badlands"]
		#The biome's matching the biome dictionary entries in which Centaur's can spawn
		centaurBiomeDictionary = ["OVERWORLD,PLAINS,!SAVANNA", "OVERWORLD,MESA"]
		#Inverts the Centaur biome list to become a blacklist instead (Does not affect tags) [default: false]
		centaurInvertList = false
		#Logs to which biomes Centaur is being added [default: false]
		centaurLogAdditions = false

	#Creep settings
	[Spawning.Creep]
		#The spawning weight of Creep's (0 = disabled) [default: 20]
		#Range: > 0
		creepWeight = 20
		#The minimum number of Creep's in a group [default: 4]
		#Range: > 1
		creepMinGroup = 4
		#The maximum number of Creep's in a group [default: 6]
		#Range: > 1
		creepMaxGroup = 6
		#The biomes where Creep's can spawn
		creepBiomes = []
		#The biome's matching the biome dictionary entries in which Creep's can spawn
		creepBiomeDictionary = ["OVERWORLD"]
		#Inverts the Creep biome list to become a blacklist instead (Does not affect tags) [default: true]
		creepInvertList = true
		#Logs to which biomes Creep is being added [default: false]
		creepLogAdditions = false

	#Cyclops settings
	[Spawning.Cyclops]
		#The spawning weight of Cyclops's (0 = disabled) [default: 40]
		#Range: > 0
		cyclopsWeight = 40
		#The minimum number of Cyclops's in a group [default: 4]
		#Range: > 1
		cyclopsMinGroup = 4
		#The maximum number of Cyclops's in a group [default: 6]
		#Range: > 1
		cyclopsMaxGroup = 6
		#The biomes where Cyclops's can spawn
		cyclopsBiomes = ["minecraft:taiga", "minecraft:snowy_taiga", "minecraft:old_growth_pine_taiga", "minecraft:old_growth_spruce_taiga"]
		#The biome's matching the biome dictionary entries in which Cyclops's can spawn
		cyclopsBiomeDictionary = ["OVERWORLD,FOREST,CONIFEROUS,!SNOWY"]
		#Inverts the Cyclops biome list to become a blacklist instead (Does not affect tags) [default: false]
		cyclopsInvertList = false
		#Logs to which biomes Cyclops is being added [default: false]
		cyclopsLogAdditions = false

	#Dryad settings
	[Spawning.Dryad]
		#The spawning weight of Dryad's (0 = disabled) [default: 60]
		#Range: > 0
		dryadWeight = 60
		#The minimum number of Dryad's in a group [default: 4]
		#Range: > 1
		dryadMinGroup = 4
		#The maximum number of Dryad's in a group [default: 6]
		#Range: > 1
		dryadMaxGroup = 6
		#The biomes where Dryad's can spawn
		dryadBiomes = ["minecraft:forest", "minecraft:birch_forest", "minecraft:old_growth_birch_forest"]
		#The biome's matching the biome dictionary entries in which Dryad's can spawn
		dryadBiomeDictionary = ["OVERWORLD,FOREST,!CONIFEROUS,!COLD,!HOT,!SPARSE,SPOOKY,!DENSE", "OVERWORLD,FOREST,DENSE,RARE,!CONIFEROUS,!COLD,!HOT,!SPARSE,SPOOKY"]
		#Inverts the Dryad biome list to become a blacklist instead (Does not affect tags) [default: false]
		dryadInvertList = false
		#Logs to which biomes Dryad is being added [default: false]
		dryadLogAdditions = false

	#Dullahan settings
	[Spawning.Dullahan]
		#The spawning weight of Dullahan's (0 = disabled) [default: 100]
		#Range: > 0
		dullahanWeight = 100
		#The minimum number of Dullahan's in a group [default: 4]
		#Range: > 1
		dullahanMinGroup = 4
		#The maximum number of Dullahan's in a group [default: 6]
		#Range: > 1
		dullahanMaxGroup = 6
		#The biomes where Dullahan's can spawn
		dullahanBiomes = ["minecraft:meadow"]
		#The biome's matching the biome dictionary entries in which Dullahan's can spawn
		dullahanBiomeDictionary = ["OVERWORLD,PLATEAU,!COLD,!HOT"]
		#Inverts the Dullahan biome list to become a blacklist instead (Does not affect tags) [default: false]
		dullahanInvertList = false
		#Logs to which biomes Dullahan is being added [default: false]
		dullahanLogAdditions = false

	#Harpy settings
	[Spawning.Harpy]
		#The spawning weight of Harpy's (0 = disabled) [default: 100]
		#Range: > 0
		harpyWeight = 100
		#The minimum number of Harpy's in a group [default: 2]
		#Range: > 1
		harpyMinGroup = 2
		#The maximum number of Harpy's in a group [default: 4]
		#Range: > 1
		harpyMaxGroup = 4
		#The biomes where Harpy's can spawn
		harpyBiomes = ["minecraft:plains", "minecraft:sunflower_plains"]
		#The biome's matching the biome dictionary entries in which Harpy's can spawn
		harpyBiomeDictionary = ["OVERWORLD,PLAINS,!SAVANNA", "OVERWORLD,MESA", "OVERWORLD,FOREST,SPOOKY"]
		#Inverts the Harpy biome list to become a blacklist instead (Does not affect tags) [default: false]
		harpyInvertList = false
		#Logs to which biomes Harpy is being added [default: false]
		harpyLogAdditions = false

	#Hunter settings
	[Spawning.Hunter]
		#The spawning weight of Hunter's (0 = disabled) [default: 60]
		#Range: > 0
		hunterWeight = 60
		#The minimum number of Hunter's in a group [default: 2]
		#Range: > 1
		hunterMinGroup = 2
		#The maximum number of Hunter's in a group [default: 4]
		#Range: > 1
		hunterMaxGroup = 4
		#The biomes where Hunter's can spawn
		hunterBiomes = ["minecraft:jungle", "minecraft:sparse_jungle", "minecraft:bamboo_jungle"]
		#The biome's matching the biome dictionary entries in which Hunter's can spawn
		hunterBiomeDictionary = ["OVERWORLD,JUNGLE"]
		#Inverts the Hunter biome list to become a blacklist instead (Does not affect tags) [default: false]
		hunterInvertList = false
		#Logs to which biomes Hunter is being added [default: false]
		hunterLogAdditions = false

	#Kobold settings
	[Spawning.Kobold]
		#The spawning weight of Kobold's (0 = disabled) [default: 60]
		#Range: > 0
		koboldWeight = 60
		#The minimum number of Kobold's in a group [default: 4]
		#Range: > 1
		koboldMinGroup = 4
		#The maximum number of Kobold's in a group [default: 6]
		#Range: > 1
		koboldMaxGroup = 6
		#The biomes where Kobold's can spawn
		koboldBiomes = ["minecraft:snowy_plains", "minecraft:snowy_slopes"]
		#The biome's matching the biome dictionary entries in which Kobold's can spawn
		koboldBiomeDictionary = ["OVERWORLD,SNOWY,!OCEAN,!RIVER,!BEACH,!FOREST"]
		#Inverts the Kobold biome list to become a blacklist instead (Does not affect tags) [default: false]
		koboldInvertList = false
		#Logs to which biomes Kobold is being added [default: false]
		koboldLogAdditions = false

	#Matango settings
	[Spawning.Matango]
		#The spawning weight of Matango's (0 = disabled) [default: 60]
		#Range: > 0
		matangoWeight = 60
		#The minimum number of Matango's in a group [default: 2]
		#Range: > 1
		matangoMinGroup = 2
		#The maximum number of Matango's in a group [default: 4]
		#Range: > 1
		matangoMaxGroup = 4
		#The biomes where Matango's can spawn
		matangoBiomes = ["minecraft:dark_forest"]
		#The biome's matching the biome dictionary entries in which Matango's can spawn
		matangoBiomeDictionary = ["OVERWORLD,FOREST,SPOOKY"]
		#Inverts the Matango biome list to become a blacklist instead (Does not affect tags) [default: false]
		matangoInvertList = false
		#Logs to which biomes Matango is being added [default: false]
		matangoLogAdditions = false

	#NineTails settings
	[Spawning.NineTails]
		#The spawning weight of NineTails's (0 = disabled) [default: 40]
		#Range: > 0
		ninetailsWeight = 40
		#The minimum number of NineTails's in a group [default: 2]
		#Range: > 1
		ninetailsMinGroup = 2
		#The maximum number of NineTails's in a group [default: 4]
		#Range: > 1
		ninetailsMaxGroup = 4
		#The biomes where NineTails's can spawn
		ninetailsBiomes = ["minecraft:snowy_taiga", "minecraft:old_growth_pine_taiga", "minecraft:old_growth_spruce_taiga"]
		#The biome's matching the biome dictionary entries in which NineTails's can spawn
		ninetailsBiomeDictionary = ["OVERWORLD,FOREST,CONIFEROUS,!SNOWY"]
		#Inverts the NineTails biome list to become a blacklist instead (Does not affect tags) [default: false]
		ninetailsInvertList = false
		#Logs to which biomes NineTails is being added [default: false]
		ninetailsLogAdditions = false

	#Oni settings
	[Spawning.Oni]
		#The spawning weight of Oni's (0 = disabled) [default: 80]
		#Range: > 0
		oniWeight = 80
		#The minimum number of Oni's in a group [default: 4]
		#Range: > 1
		oniMinGroup = 4
		#The maximum number of Oni's in a group [default: 6]
		#Range: > 1
		oniMaxGroup = 6
		#The biomes where Oni's can spawn
		oniBiomes = ["minecraft:snowy_taiga", "minecraft:old_growth_pine_taiga", "minecraft:old_growth_spruce_taiga"]
		#The biome's matching the biome dictionary entries in which Oni's can spawn
		oniBiomeDictionary = ["OVERWORLD,FOREST,CONIFEROUS,!SNOWY"]
		#Inverts the Oni biome list to become a blacklist instead (Does not affect tags) [default: false]
		oniInvertList = false
		#Logs to which biomes Oni is being added [default: false]
		oniLogAdditions = false

	#Shaman settings
	[Spawning.Shaman]
		#The spawning weight of Shaman's (0 = disabled) [default: 60]
		#Range: > 0
		shamanWeight = 60
		#The minimum number of Shaman's in a group [default: 2]
		#Range: > 1
		shamanMinGroup = 2
		#The maximum number of Shaman's in a group [default: 4]
		#Range: > 1
		shamanMaxGroup = 4
		#The biomes where Shaman's can spawn
		shamanBiomes = ["minecraft:jungle", "minecraft:sparse_jungle", "minecraft:bamboo_jungle"]
		#The biome's matching the biome dictionary entries in which Shaman's can spawn
		shamanBiomeDictionary = ["OVERWORLD,JUNGLE"]
		#Inverts the Shaman biome list to become a blacklist instead (Does not affect tags) [default: false]
		shamanInvertList = false
		#Logs to which biomes Shaman is being added [default: false]
		shamanLogAdditions = false

	#Siren settings
	[Spawning.Siren]
		#The spawning weight of Siren's (0 = disabled) [default: 60]
		#Range: > 0
		sirenWeight = 60
		#The minimum number of Siren's in a group [default: 4]
		#Range: > 1
		sirenMinGroup = 4
		#The maximum number of Siren's in a group [default: 6]
		#Range: > 1
		sirenMaxGroup = 6
		#The biomes where Siren's can spawn
		sirenBiomes = ["minecraft:swamp"]
		#The biome's matching the biome dictionary entries in which Siren's can spawn
		sirenBiomeDictionary = ["OVERWORLD,SWAMP"]
		#Inverts the Siren biome list to become a blacklist instead (Does not affect tags) [default: false]
		sirenInvertList = false
		#Logs to which biomes Siren is being added [default: false]
		sirenLogAdditions = false

	#SludgeGirl settings
	[Spawning.SludgeGirl]
		#The spawning weight of SludgeGirl's (0 = disabled) [default: 100]
		#Range: > 0
		sludgegirlWeight = 100
		#The minimum number of SludgeGirl's in a group [default: 2]
		#Range: > 1
		sludgegirlMinGroup = 2
		#The maximum number of SludgeGirl's in a group [default: 4]
		#Range: > 1
		sludgegirlMaxGroup = 4
		#The biomes where SludgeGirl's can spawn
		sludgegirlBiomes = ["minecraft:swamp"]
		#The biome's matching the biome dictionary entries in which SludgeGirl's can spawn
		sludgegirlBiomeDictionary = ["OVERWORLD,SWAMP"]
		#Inverts the SludgeGirl biome list to become a blacklist instead (Does not affect tags) [default: false]
		sludgegirlInvertList = false
		#Logs to which biomes SludgeGirl is being added [default: false]
		sludgegirlLogAdditions = false

	#Succubus settings
	[Spawning.Succubus]
		#The spawning weight of Succubus's (0 = disabled) [default: 16]
		#Range: > 0
		succubusWeight = 16
		#The minimum number of Succubus's in a group [default: 2]
		#Range: > 1
		succubusMinGroup = 2
		#The maximum number of Succubus's in a group [default: 4]
		#Range: > 1
		succubusMaxGroup = 4
		#The biomes where Succubus's can spawn
		succubusBiomes = ["minecraft:nether_wastes", "minecraft:soul_sand_valley", "minecraft:crimson_forest", "minecraft:warped_forest", "minecraft:basalt_deltas"]
		#The biome's matching the biome dictionary entries in which Succubus's can spawn
		succubusBiomeDictionary = ["NETHER"]
		#Inverts the Succubus biome list to become a blacklist instead (Does not affect tags) [default: false]
		succubusInvertList = false
		#Logs to which biomes Succubus is being added [default: false]
		succubusLogAdditions = false

	#Werecat settings
	[Spawning.Werecat]
		#The spawning weight of Werecat's (0 = disabled) [default: 80]
		#Range: > 0
		werecatWeight = 80
		#The minimum number of Werecat's in a group [default: 4]
		#Range: > 1
		werecatMinGroup = 4
		#The maximum number of Werecat's in a group [default: 6]
		#Range: > 1
		werecatMaxGroup = 6
		#The biomes where Werecat's can spawn
		werecatBiomes = ["minecraft:forest", "minecraft:birch_forest", "minecraft:old_growth_birch_forest"]
		#The biome's matching the biome dictionary entries in which Werecat's can spawn
		werecatBiomeDictionary = ["OVERWORLD,BEACH,!MUSHROOM"]
		#Inverts the Werecat biome list to become a blacklist instead (Does not affect tags) [default: false]
		werecatInvertList = false
		#Logs to which biomes Werecat is being added [default: false]
		werecatLogAdditions = false

	#YukiOnna settings
	[Spawning.YukiOnna]
		#The spawning weight of YukiOnna's (0 = disabled) [default: 60]
		#Range: > 0
		yukionnaWeight = 60
		#The minimum number of YukiOnna's in a group [default: 2]
		#Range: > 1
		yukionnaMinGroup = 2
		#The maximum number of YukiOnna's in a group [default: 4]
		#Range: > 1
		yukionnaMaxGroup = 4
		#The biomes where YukiOnna's can spawn
		yukionnaBiomes = ["minecraft:taiga", "minecraft:snowy_taiga", "minecraft:old_growth_pine_taiga", "minecraft:old_growth_spruce_taiga"]
		#The biome's matching the biome dictionary entries in which YukiOnna's can spawn
		yukionnaBiomeDictionary = ["OVERWORLD,FOREST,CONIFEROUS,!SNOWY"]
		#Inverts the YukiOnna biome list to become a blacklist instead (Does not affect tags) [default: false]
		yukionnaInvertList = false
		#Logs to which biomes YukiOnna is being added [default: false]
		yukionnaLogAdditions = false

